### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by Sohalt** [Devoxx4KidsDE/workshop-sonic-pi#5]
It would be nice to know under what license the published material may be reused (if at all).

**Comment by stefan-hoehn** [comment]
hi @Sohalt As you can see [here](http://www.devoxx4kids.org/materials/) all devoxx4kids material should be licenced under the [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-nc-sa/4.0/deed.en_US). 

Hope that helps,
Stefan

PS: I'm curious what you intend to use it for, though? :-)

**Comment by Sohalt** [comment]
Thank you, that's helpful!
Can you maybe add a `LICENSE` file to the repository nonetheless? This will allow GitHub to show the license directly in their interface making it easier for people finding the project on GitHub.

> PS: I'm curious what you intend to use it for, though? :-)

I'll be giving a workshop on teaching Sonic Pi and am looking for existing material to reference and share. Thanks for your work! It looks really solid.

**Comment by stefan-hoehn** [comment]
I looked into it right away when you were pinging me. Unfortunately, there seems to be no easy way in this case. github usually allows you to add a LICENSE file and then choose the the right license but it doesn't support that one. So I looked for the license text that I could just copy paste (e.g. I found this here: https://github.com/matthewmccullough/Creative-Commons-4.0-Markdown/blob/master/licenses/by-nc-sa.markdown) but I am not sure if that would be the right approach as the official page would ask you to just link to the license: https://creativecommons.org/licenses/by-nc-sa/4.0/

So maybe the best way is to just mention it in the Readme or does it make send to just copy the link into the LICENSE.md ?

**Comment by Sohalt** [comment]
I think creating a `LICENSE` file would still be the best way. You can find the license text on the Github run choosealicense.com  https://choosealicense.com/licenses/cc-by-sa-4.0/ and the creative commons organization are using it themselves on Github (and Github properly recognizes it): https://github.com/creativecommons/taaccct

**Comment by stefan-hoehn** [comment]
Ok, great for researching and finding it! I have added the license file.

**Comment by Sohalt** [comment]
Thanks for handling this so quickly!
